<?php
/**
 * @file
 * OOP: Design Patterns
 */

/**
 * Implements hook_theme().
 */
function bridge_pattern_theme() {
  $return = array();

  $return['bridge_pattern_content'] = array(
    'variables' => array(
      'uml_image' => NULL,
    ),
  );

  return $return;
}

function template_preprocess_bridge_pattern_content(&$variables) {
  $module_path = drupal_get_path('module', 'bridge_pattern');
  $uml_image = array(
    '#theme' => 'image',
    '#uri' => "{$module_path}/images/uml.png",
  );
  $variables['uml_image'] = render($uml_image);
}
